# Generated by Django 3.2.7 on 2021-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
