# Generated by Django 3.2.7 on 2021-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20211004_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
