# Generated by Django 3.2.7 on 2021-11-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20211004_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('discord', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='techminate/images/members/')),
                ('is_active', models.BooleanField(default=False)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.team')),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
