# Generated by Django 3.2.7 on 2021-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_member_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(upload_to='images/members/'),
        ),
    ]
