# Generated by Django 3.2.7 on 2021-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('design', 'Design'), ('website', 'Wesite'), ('app', 'App')], default='website', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/portfolio/')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
