# Generated by Django 3.2.7 on 2021-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
